export const flags = {
    INITIAL_VALUE: 'CS/FLAGS/INITIAL_VALUE',
    ERROR: 'CS/FLAGS/ERROR',
    NOT_FOUND: 'CS/FLAGS/NOT_FOUND'
};

export const app = {
    AUTHENTICATE: 'CS/APP/AUTHENTICATE',

    VERIFY_SESSION: 'CS/APP/VERIFY_SESSION',
    VERIFY_SESSION_SUCCESSFUL: 'CS/APP/VERIFY_SESSION_SUCCESSFUL',
    VERIFY_SESSION_FAILED: 'CS/APP/VERIFY_SESSION_FAILED',

    GET_FACULTIES_SUCESS: 'CS/APP/GET_FACULTIES',
    GET_DEPARTMENTS_SUCCESS: 'CS/APP/GET_DEPARTMENTS',
    GET_LEVELS_SUCCESS: 'CS/APP/GET_LEVELS',
    GET_CATEGORIES_SUCCESS: 'CS/APP/GET_CATEGORIES',

    GET_RESOURCES: 'CS/APP/GET_RESOURCES',
    SIGNAL_FETCH_DEPARTMENTS: 'CS/APP/SIGNAL_FETCH_DEPARTMENTS',
};

export const user = {
    
};

export const group = {
    
};